**Slicing

In [ ]:
import numpy as np

arr = np.random.randint(1,9, size = (3,4))

arr

In [11]:
arr[1,2]

np.int32(8)

In [16]:
arr[:,2].sum(axis = 0)

np.int64(11)

In [13]:
arr[:,-2].sum()

np.int64(11)

In [17]:
arr[1,:].sum()

np.int64(19)

In [34]:
arr[:,[1,2]].sum(axis = 0)

array([10, 11])

In [37]:
arr[1,[1,2]].sum()

np.int64(10)

In [46]:
arr[1:3,[1,2]].sum()

np.int64(15)

##Multiplication

In [15]:
arr = np.arange(0,100,4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [33]:
arr1=np.random.random((2,3,2))
arr1

array([[[0.92084773, 0.94939578],
        [0.84473462, 0.23878655],
        [0.89438051, 0.60813803]],

       [[0.84476253, 0.93190994],
        [0.28589071, 0.25592723],
        [0.81588486, 0.85970284]]])

In [60]:
mul1 = np.random.randint(1,100,size=(3,4))
mul1

array([[13, 68, 59,  4],
       [79, 70, 63, 19],
       [79,  8, 20, 10]], dtype=int32)

In [61]:
mul2 = np.random.randint(10,200,size=(4,5))
mul2

array([[ 19, 108,  38, 151, 173],
       [134, 155, 131,  26, 162],
       [178, 115, 125, 162,  12],
       [ 83, 191, 146,  15, 172]], dtype=int32)

In [63]:
np.matmul(mul1,mul2)

array([[20193, 19493, 17361, 13349, 14661],
       [23672, 30256, 22821, 24240, 29031],
       [ 6963, 13982,  8010, 15527, 16923]], dtype=int32)

In [84]:
con1 = np.arange(4,100,5).reshape(4,5)
con1

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

In [78]:
con2 = np.arange(0,100,4).reshape(5,5)
con2

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [92]:
con = np.concatenate((con1,con2),axis = 0)

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99],
       [ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [94]:
con[6,2]

np.int64(48)

In [103]:
fil = con1>90
con1[fil]

array([94, 99])

In [120]:
tran = np.arange(0,12,2).reshape(2,3)
tran

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [122]:
np.transpose(tran)

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

In [126]:
res = np.arange(0,100,5).reshape(4,5)
res

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [129]:
res[0:4,1:]

array([[ 5, 10, 15, 20],
       [30, 35, 40, 45],
       [55, 60, 65, 70],
       [80, 85, 90, 95]])